# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

continueOnError: true
name: $(majorMinorVersion).$(semanticVersion)-$(designation)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorMinorVersion: 0.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  designation: 'alpha'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: NuGetCommand@2
  displayName: 'Nuget pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/Tech.SmsMessageMinimiser.csproj'
    versioningScheme: byEnvVar
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versionEnvVar: BUILDNO
    buildProperties: PackageProjectUrl=https://github.com/carlbm/sms-message-minimiser;PackageIconUrl=https://github.com/carlbm/sms-message-minimiser/blob/master/logo.png
    

- task: NuGetCommand@2
  displayName: 'NuGet publish'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/Tech.SmsMessageMinimiser*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '33312d7f-ae99-4c36-ba06-9c6bca94148e'
    verbosityPush: 'Normal'
    
